<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <link rel="stylesheet" href="index.css">
</head>
<body>
<div>
    <h1> Имя кота: ${cat1.name}, Вес кота: ${cat1.weight} </h1>
    <h2> Имя кота: ${cat2.name}, Вес кота: ${cat3.weight}  </h2>
    <h3> Имя кота: ${cat3.name}, Вес кота: ${cat3.weight} </h3>
</div>

<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"> Видео со смешными котиками</a>
<p> (=^･ｪ･^=) </p>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCIMmF5-7vX-EDKqZUQ_fUMA58IinyPB1dnA&usqp=CAU"> </img>
</body>
</html>